option('xwayland', type : 'feature', value : 'enabled')
option('asan', type : 'boolean', value : false)
option('frametail', type : 'feature', value : 'disabled', description : 'Frametail server-side decorations')
option('compositor_name', type : 'string', value : 'elderberry', description : 'Installed compositor executable name')
